"use client";

import Link from "next/link";
import { useInquiries } from "@/features/inquiries/hooks/use-inquiries";

export function RecentInquiries(){
  const{data=[],isLoading,error}=useInquiries();
  const recent=[...data].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()).slice(0,8);
  return <section className="dashboard-panel overflow-hidden rounded border border-line bg-white px-4 py-6 sm:px-7"><div className="mb-5 flex items-center justify-between"><div><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-green-500"/><p className="text-base text-gold">Client Activity</p></div><h2 className="mt-1 font-inter text-2xl font-normal">Recent Inquiries</h2><p className="mt-1 text-xs text-muted">Live data from customer contact submissions</p></div><Link href="/inquiries" className="font-inter font-semibold text-gold hover:underline">View All</Link></div><div className="overflow-x-auto">{isLoading?<p className="p-8 text-center text-muted">Loading recent inquiries…</p>:error?<p role="alert" className="p-8 text-center text-danger">{error.message}</p>:<><table className="min-w-[880px] w-full text-left"><thead className="text-muted"><tr className="border-b border-line"><th className="p-4 text-center font-normal">Client</th><th className="p-4 text-center font-normal">Inquiry Type</th><th className="p-4 text-center font-normal">Budget</th><th className="p-4 text-center font-normal">Submitted</th><th className="p-4 text-center font-normal">Status</th></tr></thead><tbody>{recent.map(item=><tr key={item._id} className="border-b border-line"><td className="p-4 text-center"><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-muted">{item.email}</p></td><td className="p-4 text-center">{item.primaryGoal}</td><td className="p-4 text-center">{item.budget}</td><td className="p-4 text-center">{new Date(item.createdAt).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})}</td><td className="p-4 text-center"><span className={`rounded-full px-3 py-1.5 text-xs font-semibold uppercase ${item.status==="completed"?"bg-green-50 text-green-700":"bg-[#F8F1DF] text-[#8A7118]"}`}>{item.status}</span></td></tr>)}</tbody></table>{!recent.length&&<p className="p-8 text-center text-muted">No customer inquiries have been submitted yet.</p>}</>}</div></section>;
}
