"use client";
import Image from "next/image";
import Link from "next/link";
import { ChangeEvent, FormEvent, ReactNode, useRef, useState } from "react";
import { OverviewHeader } from "@/features/overview/components/OverviewHeader";
import { OverviewSidebar } from "@/features/overview/components/OverviewSidebar";
import { useCreateDevelopment } from "../hooks/use-developments";
import type { DevelopmentPayload } from "../types/development.types";

type ImageItem={id:string;url:string}; type Plan={id:string;residenceType:string;bedrooms:string;bathrooms:string;interiorSize:string;terraceSize:string;startingPrice:string;status:"available"|"sold";floorPlan:string}; type Fact={id:string;label:string;value:string;description:string}; type Story={id:string;title:string;body:string;image:string;imagePosition:"left"|"right"}; type Card={id:string;title:string;description:string};
const id=()=>crypto.randomUUID(), plan=():Plan=>({id:id(),residenceType:"",bedrooms:"",bathrooms:"",interiorSize:"",terraceSize:"",startingPrice:"",status:"available",floorPlan:""}), fact=():Fact=>({id:id(),label:"",value:"",description:""}), card=():Card=>({id:id(),title:"",description:""});
const input="mt-2 h-11 w-full rounded border border-line bg-white px-3 text-sm outline-none focus:border-gold focus:ring-2 focus:ring-gold/20", area="mt-2 min-h-24 w-full rounded border border-line bg-white p-3 text-sm outline-none focus:border-gold focus:ring-2 focus:ring-gold/20", split=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
const amenityOptions=["swimming pool","spa","fitness center","yoga studio","business center","private lounge","restaurant","concierge","pet friendly","parking","private marina","childrens area","outdoor kitchen","wine lounge","game room"] as const;
function isMapUrl(value:string){try{const url=new URL(value);const host=url.hostname.toLowerCase();return url.protocol==="https:"&&(host.includes("google")||host.includes("maps")||host.includes("mapbox")||host.includes("openstreetmap"));}catch{return false}}

export function AddDevelopmentPage(){
 const create=useCreateDevelopment(),fileInput=useRef<HTMLInputElement>(null);
 const [images,setImages]=useState<ImageItem[]>([]),[plans,setPlans]=useState<Plan[]>([plan()]),[facts,setFacts]=useState<Fact[]>([fact()]),[stories,setStories]=useState<Story[]>([]),[highlights,setHighlights]=useState<Card[]>([]),[amenityCards,setAmenityCards]=useState<Card[]>([]),[uploading,setUploading]=useState(false),[message,setMessage]=useState("");
 const [f,setF]=useState({developmentName:"",propertySlug:"",selectedNeighbourhood:"",address:"",city:"",startingPrice:"",constructionStage:"pre-construction",deliveryYear:"",developer:"",pricePerSqft:"",bedrooms:"",stories:"",totalResidencies:"",sizeRange:"",shortIntroduction:"",projectOverview:"",amenities:"",category:"luxury",features:"",depositStructure:"",salesProgress:"",rentalPolicy:"",mapEmbedUrl:"",locationTitle:"",locationDescription:"",amenitiesTitle:"",amenitiesDescription:"",tourTitle:"",tourDescription:"",agentName:"",agentTitle:"",agentBio:"",agentPhone:"",agentEmail:""});
 const set=(k:keyof typeof f,v:string)=>setF(o=>({...o,[k]:v})), image=(i:number)=>images[i]?.url||"";
 const mapError=f.mapEmbedUrl&&!isMapUrl(f.mapEmbedUrl)?"Enter a valid map URL from Google Maps, Mapbox, or OpenStreetMap.":"";
 const toggleAmenity=(option:string,checked:boolean)=>{const selected=split(f.amenities);set("amenities",(checked?[...selected,option]:selected.filter(item=>item!==option)).join(","));};
 async function upload(e:ChangeEvent<HTMLInputElement>){if(!e.target.files?.length)return;setUploading(true);setMessage("");try{const d=new FormData();[...e.target.files].forEach(x=>d.append("images",x));const r=await fetch("/api/uploads/images",{method:"POST",body:d}),p=await r.json();if(!r.ok)throw new Error(p.message||"Image upload failed");setImages(o=>[...o,...p.data.map((x:{url:string})=>({id:id(),url:x.url}))]);}catch(x){setMessage(x instanceof Error?x.message:"Image upload failed")}finally{setUploading(false);e.target.value=""}}
 async function submit(e:FormEvent){e.preventDefault();setMessage("");if(mapError)return setMessage(mapError);if(!image(0))return setMessage("Upload at least one image; the first is the hero image.");const payload:DevelopmentPayload={...f,startingPrice:Number(f.startingPrice),pricePerSqft:Number(f.pricePerSqft),stories:Number(f.stories),totalResidencies:Number(f.totalResidencies),constructionStage:f.constructionStage as DevelopmentPayload["constructionStage"],heroImage:image(0),galleryImages:images.map((x,index)=>({url:x.url,index})),amenities:split(f.amenities),category:split(f.category) as DevelopmentPayload["category"],features:split(f.features),residences:plans.map(({id,startingPrice,...x})=>({...x,startingPrice:Number(startingPrice)})),detailPage:{keyFacts:facts.filter(x=>x.label&&x.value).map(({id,...x})=>x),editorialSections:stories.filter(x=>x.title&&x.body).map(({id,...x})=>x),highlights:highlights.filter(x=>x.title).map(({id,...x})=>x),gallery:images.slice(1).map((x,index)=>({url:x.url,index})),location:{title:f.locationTitle||undefined,description:f.locationDescription||undefined,mapEmbedUrl:f.mapEmbedUrl||undefined,neighbourhoodImages:images.slice(1,5).map((x,index)=>({url:x.url,index}))},amenitiesSection:{title:f.amenitiesTitle||undefined,description:f.amenitiesDescription||undefined,coverImage:image(1)||undefined,items:amenityCards.filter(x=>x.title).map(({id,title,description})=>({name:title,description:description||undefined}))},tourCta:{title:f.tourTitle||undefined,description:f.tourDescription||undefined,backgroundImage:image(2)||image(0),buttonLabel:"Schedule a tour",buttonUrl:"/contact"},agent:f.agentName?{name:f.agentName,title:f.agentTitle||undefined,bio:f.agentBio||undefined,phone:f.agentPhone||undefined,email:f.agentEmail||undefined,photo:image(3)||undefined}:undefined}};try{await create.mutateAsync(payload);setMessage("Development published successfully.")}catch(x){setMessage(x instanceof Error?x.message:"Could not publish development")}}
 return <div className="min-h-dvh bg-canvas text-ink lg:flex"><OverviewSidebar active="Developments"/><div className="min-w-0 flex-1"><OverviewHeader title="Add Development" description="Create each section of the public development-detail page."/><main className="mx-auto max-w-[1620px] px-5 py-6 sm:px-8"><form onSubmit={submit} className="overflow-hidden rounded border border-line bg-white">
 <Section title="Project essentials" hint="Hero details, headline, price and key project information."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{([["developmentName","Development name"],["propertySlug","Property slug"],["selectedNeighbourhood","Neighbourhood ID"],["developer","Developer"],["address","Address"],["city","City"],["startingPrice","Starting price"],["pricePerSqft","Price per sqft"],["deliveryYear","Delivery year"],["bedrooms","Bedroom range"],["stories","Stories"],["totalResidencies","Total residences"],["sizeRange","Size range"]] as [keyof typeof f,string][]).map(([k,l])=><Field key={k} label={l}><input required={!["bedrooms","sizeRange"].includes(k)} value={f[k]} onChange={e=>set(k,e.target.value)} className={input} type={["startingPrice","pricePerSqft","stories","totalResidencies"].includes(k)?"number":"text"} min={["startingPrice","pricePerSqft","stories","totalResidencies"].includes(k)?0:undefined} step={["startingPrice","pricePerSqft"].includes(k)?"0.01":"1"} inputMode={["startingPrice","pricePerSqft","stories","totalResidencies"].includes(k)?"decimal":undefined}/></Field>)}<Field label="Construction stage"><select value={f.constructionStage} onChange={e=>set("constructionStage",e.target.value)} className={input}><option value="pre-construction">Pre-construction</option><option value="under construction">Under construction</option><option value="move in ready">Move in ready</option></select></Field></div><Field label="Short introduction" className="mt-5"><textarea required value={f.shortIntroduction} onChange={e=>set("shortIntroduction",e.target.value)} className={area}/></Field><Field label="Project overview" className="mt-5"><textarea required value={f.projectOverview} onChange={e=>set("projectOverview",e.target.value)} className={area}/></Field></Section>
 <Section title="Cloudinary media library" hint="First image becomes the hero; other uploads power the gallery, amenities, tour and agent sections."><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" multiple className="sr-only" onChange={upload}/><button type="button" onClick={()=>fileInput.current?.click()} disabled={uploading} className="min-h-11 rounded bg-gold px-5 text-sm font-semibold text-white disabled:opacity-60">{uploading?"Uploading…":"Upload images"}</button><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{images.map((x,i)=><article key={x.id} className="relative overflow-hidden rounded border border-line"><Image src={x.url} alt={"Uploaded development image "+(i+1)} width={640} height={480} className="aspect-[4/3] w-full object-cover"/><span className="absolute left-2 top-2 rounded bg-ink px-2 py-1 text-xs text-white">{i===0?"Hero":"Media "+(i+1)}</span><button aria-label={"Remove image "+(i+1)} type="button" onClick={()=>setImages(o=>o.filter(y=>y.id!==x.id))} className="absolute right-2 top-2 min-h-11 rounded bg-white px-3 text-xs font-semibold text-danger">Remove</button></article>)}</div></Section>
 <Section title="Facts, stories & highlights" hint="The key fact row and image/text editorial blocks shown in the supplied design."><Repeater label="Key facts" add="Add fact" items={facts} setItems={setFacts} create={fact}>{(x,update)=><div className="grid gap-3 md:grid-cols-3"><input value={x.label} onChange={e=>update({label:e.target.value})} className={input} placeholder="Label"/><input value={x.value} onChange={e=>update({value:e.target.value})} className={input} placeholder="Value"/><input value={x.description} onChange={e=>update({description:e.target.value})} className={input} placeholder="Optional description"/></div>}</Repeater><Repeater label="Editorial sections" add="Add story section" items={stories} setItems={setStories} create={()=>({id:id(),title:"",body:"",image:image(1),imagePosition:"right" as const})}>{(x,update)=><div className="grid gap-3 md:grid-cols-2"><input value={x.title} onChange={e=>update({title:e.target.value})} className={input} placeholder="Section title"/><select value={x.image} onChange={e=>update({image:e.target.value})} className={input}><option value="">No image</option>{images.map((a,i)=><option key={a.id} value={a.url}>Media {i+1}</option>)}</select><textarea value={x.body} onChange={e=>update({body:e.target.value})} className={area+" md:col-span-2"} placeholder="Long-form story"/><select value={x.imagePosition} onChange={e=>update({imagePosition:e.target.value as "left"|"right"})} className={input}><option value="right">Image right</option><option value="left">Image left</option></select></div>}</Repeater><Repeater label="Highlights" add="Add highlight" items={highlights} setItems={setHighlights} create={card}>{(x,update)=><div className="grid gap-3 md:grid-cols-2"><input value={x.title} onChange={e=>update({title:e.target.value})} className={input} placeholder="Highlight title"/><input value={x.description} onChange={e=>update({description:e.target.value})} className={input} placeholder="Description"/></div>}</Repeater></Section>
 <Section title="Availability & floor plans" hint="Each floor plan becomes an availability-table row."><Repeater label="Floor plans" add="Add another floor plan" items={plans} setItems={setPlans} create={plan}>{(x,update)=><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{(["residenceType","bedrooms","bathrooms","interiorSize","terraceSize","startingPrice","floorPlan"] as (keyof Omit<Plan,"id"|"status">)[]).map(k=><input key={k} value={x[k]} onChange={e=>update({[k]:e.target.value})} className={input} placeholder={k.replace(/([A-Z])/g," $1")}/>) }<select value={x.status} onChange={e=>update({status:e.target.value as Plan["status"]})} className={input}><option value="available">Available</option><option value="sold">Sold</option></select></div>}</Repeater></Section>
 <Section title="Map, amenities, tour & agent" hint="Optional lower-page modules. Uploaded media is selected automatically by its order."><div className="grid gap-4 md:grid-cols-2"><Field label="Map embed URL"><input value={f.mapEmbedUrl} onChange={e=>set("mapEmbedUrl",e.target.value)} className={input} type="url" placeholder="https://www.google.com/maps/embed?..." aria-invalid={Boolean(mapError)} aria-describedby="map-url-error"/><span id="map-url-error" className="mt-2 block text-xs font-normal text-danger">{mapError}</span></Field>{([["locationTitle","Location section title"],["locationDescription","Location description"],["amenitiesTitle","Amenities section title"],["amenitiesDescription","Amenities description"],["tourTitle","Tour CTA title"],["tourDescription","Tour CTA description"],["agentName","Agent name"],["agentTitle","Agent title"],["agentPhone","Agent phone"],["agentEmail","Agent email"],["agentBio","Agent biography"]] as [keyof typeof f,string][]).map(([k,l])=><Field key={k} label={l}><input value={f[k]} onChange={e=>set(k,e.target.value)} className={input} type={k==="agentEmail"?"email":"text"}/></Field>)}</div><Repeater label="Amenity cards" add="Add amenity" items={amenityCards} setItems={setAmenityCards} create={card}>{(x,update)=><div className="grid gap-3 md:grid-cols-2"><input value={x.title} onChange={e=>update({title:e.target.value})} className={input} placeholder="Amenity name"/><input value={x.description} onChange={e=>update({description:e.target.value})} className={input} placeholder="Description"/></div>}</Repeater></Section>
 <Section title="Search filters & commercial details"><div className="grid gap-4 md:grid-cols-2"><Field label="Amenities"><div role="group" aria-describedby="amenities-help" className="mt-2 grid max-h-64 grid-cols-1 gap-2 overflow-y-auto rounded border border-line bg-white p-3 sm:grid-cols-2 xl:grid-cols-3">{amenityOptions.map(option=><label key={option} className="flex min-h-11 cursor-pointer items-center gap-3 rounded px-3 text-sm font-normal transition-colors hover:bg-gold/10"><input type="checkbox" checked={split(f.amenities).includes(option)} onChange={e=>toggleAmenity(option,e.target.checked)} className="h-4 w-4 accent-gold"/><span>{option}</span></label>)}</div><span id="amenities-help" className="mt-2 block text-xs font-normal text-muted">Select one or more amenities.</span></Field><Field label="Category"><select value={f.category} onChange={e=>set("category",e.target.value)} className={input}><option value="luxury">Luxury</option><option value="waterfront">Waterfront</option></select></Field>{([["features","Features (comma-separated)"],["depositStructure","Deposit structure"],["salesProgress","Sales progress"],["rentalPolicy","Rental policy"]] as [keyof typeof f,string][]).map(([k,l])=><Field key={k} label={l}><input required value={f[k]} onChange={e=>set(k,e.target.value)} className={input}/></Field>)}</div></Section>
 <footer className="flex flex-wrap items-center justify-between gap-4 border-t border-line px-6 py-5"><p role="status" className={message.includes("success")?"text-sm text-green-700":"text-sm text-danger"}>{message||images.length+" images · "+plans.length+" floor plans"}</p><div className="flex gap-3"><Link href="/developments" className="min-h-11 rounded border-2 border-gold px-5 py-3 text-sm font-semibold text-gold">Cancel</Link><button disabled={create.isPending||uploading} className="min-h-11 rounded bg-gold px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{create.isPending?"Publishing…":"Publish development"}</button></div></footer>
 </form></main></div></div>
}
function Field({label,children,className=""}:{label:string;children:ReactNode;className?:string}){return <label className={"block text-sm font-semibold "+className}>{label}{children}</label>}
function Section({title,hint,children}:{title:string;hint?:string;children:ReactNode}){return <section className="border-b border-line px-6 py-7 sm:px-8"><h2 className="font-display text-2xl font-bold">{title}</h2>{hint&&<p className="mt-1 text-sm text-muted">{hint}</p>}<div className="mt-5">{children}</div></section>}
function Repeater<T extends{id:string}>({label,add,items,setItems,create,children}:{label:string;add:string;items:T[];setItems:(v:T[]|((old:T[])=>T[]))=>void;create:()=>T;children:(x:T,update:(v:Partial<T>)=>void)=>ReactNode}){return <fieldset className="mt-7"><legend className="font-semibold">{label}</legend><div className="mt-3 space-y-3">{items.map((x,i)=><div key={x.id} className="rounded border border-line p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wide text-muted">{label} {i+1}</p>{items.length>1&&<button type="button" onClick={()=>setItems(o=>o.filter(y=>y.id!==x.id))} className="min-h-11 text-sm font-semibold text-danger">Remove</button>}</div>{children(x,next=>setItems(o=>o.map(y=>y.id===x.id?{...y,...next}:y)))}</div>)}</div><button type="button" onClick={()=>setItems(o=>[...o,create()])} className="mt-3 min-h-11 rounded border border-gold px-4 text-sm font-semibold text-gold">{add}</button></fieldset>}
